const user = [
  {
    id: 1,
    username: "mledekker0",
    email: "blynde0@ca.gov",
    password: "nF6&gbV4zi+7h",
    favorite: [5],
  },
  {
    id: 2,
    username: "dfricker1",
    email: "jnairns1@microsoft.com",
    password: "nT2$iF5+Z{DxJ6j",
    favorite: [4, 5],
  },
  {
    id: 3,
    username: "wcrudge2",
    email: "sjanuary2@trellian.com",
    password: "yA1+R@MTlGyrog*X",
    favorite: [5],
  },
  {
    id: 4,
    username: "kebbin3",
    email: "apopplewell3@miitbeian.gov.cn",
    password: "hJ4/=Y_lHN+",
    favorite: [1, 5],
  },
  {
    id: 5,
    username: "hmcisaac4",
    email: "cgoligher4@vistaprint.com",
    password: "pR1%X1~5Xe",
    favorite: [],
  },
  {
    id: 6,
    username: "clanfranchi5",
    email: "gpalliser5@msu.edu",
    password: "cK3.QO>}%",
    favorite: [9],
  },
  {
    id: 7,
    username: "fcurme6",
    email: "gmeier6@last.fm",
    password: "nV4)mSgmnmZBd=?u",
    favorite: [],
  },
  {
    id: 8,
    username: "rbrookshaw7",
    email: "jbarajaz7@aol.com",
    password: 'yR9">w~<=8',
    favorite: [],
  },
  {
    id: 9,
    username: 1,
    email: "etilby8@samsung.com",
    password: "eL9@.!j>",
    favorite: [11, 13],
  },
  {
    id: 10,
    username: "gbarock9",
    email: "fabramowsky9@jalbum.net",
    password: "fD0#*OdgZ.Bg(",
    favorite: [],
  },
  {
    id: 11,
    username: "npurnella",
    email: "dclaidena@psu1",
    password: "bI0#*#v}k,",
    favorite: [9, 15],
  },
  {
    id: 12,
    username: "cgoodliffb",
    email: "jdebankeb@xing.com",
    password: "tJ3=G(rqXtnIWib/",
    favorite: [],
  },
  {
    id: 13,
    username: "ngullisc",
    email: "dcherryc@mac.com",
    password: "sD6'oKZ#%GN",
    favorite: [],
  },
  {
    id: 14,
    username: "sbrittonerd",
    email: "amcareed@adobe.com",
    password: "fB2`2<2)",
    favorite: [16],
  },
  {
    id: 15,
    username: "hdomnine",
    email: "msollowayee@nature.com",
    password: "oX3>'tsz$h+\"8hJ",
    favorite: [],
  },
  {
    id: 16,
    username: "tdudhillf",
    email: "mextonf@4shared.com",
    password: 'mP8$?)w1"',
    favorite: [16, 20],
  },
  {
    id: 17,
    username: "thalfacreg",
    email: "hpetrosellig@china.com.cn",
    password: "eK1@~caS_SW",
    favorite: [],
  },
  {
    id: 18,
    username: "kaugustush",
    email: "zmephamh@comcast.net",
    password: 'iJ2%"p#v~6',
    favorite: [],
  },
  {
    id: 19,
    username: "mallatti",
    email: "bfaini@economist.com",
    password: "wV3)NcZNvRcv$1X",
    favorite: [],
  },
  {
    id: 20,
    username: "lapsj",
    email: "abiaggiottij@ucsd.edu",
    password: "iB7@7uuEtlf.qk",
    favorite: [],
  },
];
module.exports = user;
