const starterRestaurant = [
  {
    restaurantId: "1",
    name: "Lemongrass Haven",
    cuisine: "Thai",
    location: "Ciengang",
    averageRating: 4.3,
    reviews: ["1", "6", "11", "16"],
  },
  {
    restaurantId: "2",
    name: "Sakura Sky",
    cuisine: "Japanese",
    location: "Ogurugu",
    averageRating: 4.8,
    reviews: ["2", "7", "12", "17"],
  },
  {
    restaurantId: "3",
    name: "Laksa Lounge",
    cuisine: "Malaysian",
    location: "Chodzież",
    averageRating: 4.5,
    reviews: ["3", "8", "13", "18"],
  },
  {
    restaurantId: "4",
    name: "Wasabi Wave",
    cuisine: "Japanese",
    location: "Sa Bot",
    averageRating: 3.9,
    reviews: ["4", "9", "14", "19"],
  },
  {
    restaurantId: "5",
    name: "Route 66 Diner",
    cuisine: "American",
    location: "Büzmeýin",
    averageRating: 3.8,
    reviews: ["5", "10", "15", "20"],
  },
  {
    restaurantId: "6",
    name: "Penang Spice",
    cuisine: "Malaysian",
    location: "Lianhe",
    averageRating: 3.1,
    reviews: [],
  },
  {
    restaurantId: "7",
    name: "Spice Symphony",
    cuisine: "Indian",
    location: "Bolembre",
    averageRating: 3.3,
    reviews: [],
  },
  {
    restaurantId: "8",
    name: "Zen Ramen Bar",
    cuisine: "Japanese",
    location: "La Mesa",
    averageRating: 2.7,
    reviews: [],
  },
  {
    restaurantId: "9",
    name: "Red Dragon Table",
    cuisine: "Chinese",
    location: "Torslanda",
    averageRating: 4.0,
    reviews: [],
  },
  {
    restaurantId: "10",
    name: "Siam Delight",
    cuisine: "Thai",
    location: "Elías",
    averageRating: 2.3,
    reviews: [],
  },
  {
    restaurantId: "11",
    name: "Tandoor Tales",
    cuisine: "Indian",
    location: "Huangbei",
    averageRating: 4.3,
    reviews: [],
  },
  {
    restaurantId: "12",
    name: "Hikari Sushi",
    cuisine: "Japanese",
    location: "Xianqiao",
    averageRating: 4.2,
    reviews: [],
  },
  {
    restaurantId: "13",
    name: "Golden Elephant",
    cuisine: "Thai",
    location: "Tinghir",
    averageRating: 4.6,
    reviews: [],
  },
  {
    restaurantId: "14",
    name: "Matcha Moon",
    cuisine: "Japanese",
    location: "Guisguis",
    averageRating: 3.8,
    reviews: [],
  },
  {
    restaurantId: "15",
    name: "Curry Leaf Bistro",
    cuisine: "Indian",
    location: "Bin’an",
    averageRating: 4.3,
    reviews: [],
  },
  {
    restaurantId: "16",
    name: "Bamboo Breeze",
    cuisine: "Thai",
    location: "Xinhuang",
    averageRating: 4.3,
    reviews: [],
  },
  {
    restaurantId: "17",
    name: "Grill & Chill",
    cuisine: "American",
    location: "Josefův Důl",
    averageRating: 3.3,
    reviews: [],
  },
  {
    restaurantId: "18",
    name: "Golden Wok Dynasty",
    cuisine: "Chinese",
    location: "Fujinomiya",
    averageRating: 3.8,
    reviews: [],
  },
  {
    restaurantId: "19",
    name: "Songkran Kitchen",
    cuisine: "Thai",
    location: "Campos Novos",
    averageRating: 3.7,
    reviews: [],
  },
  {
    restaurantId: "20",
    name: "Liberty Bites",
    cuisine: "American",
    location: "Ivanovka",
    averageRating: 4.9,
    reviews: [],
  },
];
module.exports = starterRestaurant;
